services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: mlite_php
    volumes:
      - ../:/var/www/public       # <== BENAR, karena file ini di dalam /docker/
    depends_on:
      - mysql
    networks:
      app-network:
        ipv4_address: 10.20.0.6
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: unless-stopped

  panel:
    build:
      context: ./panel
      dockerfile: Dockerfile
    container_name: mlite_panel
    ports:
      - "5001:5000"
    volumes:
      - ./panel:/app
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dns:/app/dns  # DNS management access
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_CONTAINER_NAME=mlite_nginx
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: mlite_nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ../:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - panel
    networks:
      app-network:
        ipv4_address: 10.20.0.5
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mlite_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mlite
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ../mlite_db.sql:/docker-entrypoint-initdb.d/00-mlite_db.sql
      - ./db:/docker-entrypoint-initdb.d/01-custom
    networks:
      - app-network

  orthanc:
    build:
      context: .
      dockerfile: orthanc/Dockerfile
    container_name: mlite_orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc-db:/var/lib/orthanc/db
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    environment:
      - ORTHANC_NAME=Orthanc-Headless
    networks:
      - app-network

  dns:
    image: 4km3/dnsmasq:latest
    container_name: mlite_dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dns/dnsmasq.hosts:/etc/dnsmasq.hosts
      - ./dns/dnsmasq.log:/var/log/dnsmasq.log
    environment:
      - DNSMASQ_CONF=/etc/dnsmasq.conf
    networks:
      app-network:
        ipv4_address: 10.20.0.10
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1
