services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: mlite_php
    volumes:
      - ../:/var/www/public       # <== BENAR, karena file ini di dalam /docker/
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: mlite_nginx
    ports:
      - "8080:80"                 # <== disarankan pakai 8080 agar tidak bentrok port 80 host
    volumes:
      - ../:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mlite_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mlite
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ../mlite_db.sql:/docker-entrypoint-initdb.d/00-mlite_db.sql
      - ./db:/docker-entrypoint-initdb.d/01-custom
    networks:
      - app-network

  orthanc:
    build:
      context: .
      dockerfile: orthanc/Dockerfile
    container_name: mlite_orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc-db:/var/lib/orthanc/db
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    environment:
      - ORTHANC_NAME=Orthanc-Headless
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
